globstatsfile: replace newline by space

diff --git a/rhefo b/rhefo
--- a/rhefo
+++ b/rhefo
@@ -238,10 +238,10 @@ parseArgs() {  # not using `local` vars because this fct is only executed once
 	for i do [ -r "$i" ] || error "Input '$i' does not exist or cannot read it."; done
 
 	# create all the dir-tree to output folder
-	[ -v globoutput ] && { for i do [ -d "$i" ] && ( [ "${globoutput#$(realpath -- "$i")}" = "$globoutput" ] || error "The --glob-output folder can't be inside an input folder."; cd -- "$i"; find . -type d -exec mkdir -p "$globoutput/$(basename "$(realpath -- "$i")")/{}" \;; cd ~-;}; done;}
+	[ -v globoutput ] && { for i do [ -d "$i" ] && { [ "${globoutput#$(realpath -- "$i")}" = "$globoutput" ] || error "The --glob-output folder can't be inside an input folder."; cd -- "$i"; find . -type d -exec mkdir -p "$globoutput/$(basename "$(realpath -- "$i")")/{}" \;; cd ~-;}; done;}
 	TMPDIR=$(mktemp --tmpdir -d .rhefo_${version}_tmpXXX)
 
-	printf '0\n0\n0\n' >"${globstatsfile=$(mktemp --tmpdir XXX)}"  # file where stats are wrote - to allow edit in subshells since we use `parallel`; 1st line is saved bytes, 2nd is input files size, 3rd is nbr input files
+	echo '0 0 0' >"${globstatsfile=$(mktemp --tmpdir XXX)}"  # file where stats are wrote - to allow edit in subshells since we use `parallel`; 1st line is saved bytes, 2nd is input files size, 3rd is nbr input files
 
 	addinsDir=$(mktemp -dp/tmp rhefo_${version}_tmpXXX)  # use /tmp for temp dir because we don't want weird chars (like ':') since we add it to PATH
 	PATH=$addinsDir:$PATH
@@ -589,7 +589,7 @@ compressFile() {
 	[ -v globkeeptime ] && touch -md"$mtime" "$tmp" && touch -ad"$atime" "$tmp"
 	if [ -v isEmbeddedFile ]
 	then mv "$tmp" "$out"
-	else sem --fg --id "$globstatsfile" 'set -- $(<"$globstatsfile"); printf "$(('$size'+$1))\n$(('$3'+$2))\n$((1+$3))\n" >"$globstatsfile"'  # use a semaphore to allow only one thread to write stats at a time
+	else sem --fg --id "$globstatsfile" 'set -- $(<"$globstatsfile"); echo "$(('$size'+$1)) $(('$3'+$2)) $((1+$3))" >"$globstatsfile"'  # use a semaphore to allow only one thread to write stats at a time
 		if [[ -v globoutput && ! -v globupdate && -e "$out" ]]
 		then warning "'$out' already exists, not updated. Compressed version here: '$tmp'." 'Rerun with -f to overwrite files in output directory, or with -p to add a prefix.'  # TODO not remove with below rm -r
 		else mv "$tmp" "$out"
@@ -606,14 +606,14 @@ compressTmpFolder() {
 	[ -v globnoextract ] || find "$1" -type f -printf '%s\0%P\0%H\0' | sortFilesBySize | parallel -0L3 --lb globkeeptime= compressFile {2} {3}
 }
 
-info() { printf "\r\033[1;36mI: %s\033[0m\n" "$@";}
+info() { printf '\r\033[1;36mI: %s\033[0m\n' "$@";}
 
-warning() { printf "\r\033[1;33mW: %s\033[0m\n" "$@" >&2;}
+warning() { printf '\r\033[1;33mW: %s\033[0m\n' "$@" >&2;}
 
 error() {  # TODO change this to have exit code as first argument (so we could simply use shift)
 	if [[ ${@: -1} = +([0-9]) ]]  # check if last arg is a number (== exit code)
-	then printf "\r\033[1;31mE: %s\033[0m\n" "${@:1:$#-1}" >&2; exit ${@: -1}
-	else printf "\r\033[1;31mE: %s\033[0m\n" "$@" >&2; exit 1
+	then printf '\r\033[1;31mE: %s\033[0m\n' "${@:1:$#-1}" >&2; exit ${@: -1}
+	else printf '\r\033[1;31mE: %s\033[0m\n' "$@" >&2; exit 1
 	fi
 }
 
