command not found handler

diff --git a/rhefo b/rhefo
--- a/rhefo
+++ b/rhefo
@@ -52,6 +52,16 @@
 set -a  # export var+fct automatically
 set -m  # All processes run in a separate process group (needed for Ctrl+C "trick")
 version=0.0.1
+
+command_not_found_handle() {
+	warning "$1"$': command not found.\nInstall the needed package, this script will resume automatically.'
+	until command -v "$1" >/dev/null
+	do sleep 3;
+	done
+	info "$1: found! Resuming optimization."
+	"$@"
+}
+
 help=$(echo 'Really High Efficient File Optimizer (RHEFO), version '$version'. Under SSPL.
 For updates, supported files, dependencies, issues, license and many more, see:
   https://github.com/T-3B/rhefo
@@ -82,7 +92,7 @@ List of options (global ones first, then grouped by file type):
   if set, all lossy flags are set (except the more agressive --glob-strip)
   lossy flags *only* act on metadata; most of time they remove what
     is not really needed (such as the version of FLAC encoder)
---glob-noextract | -E		worse compression, faster
+--glob-noextract | -E	worse compression, faster
   if set, do not compress embedded files (no "recursion")
 --glob-nosort | -S
   if set, optimize files in the given order; default: sort by size (largest 1st)
@@ -208,18 +218,18 @@ parseArgs() {  # not using `local` vars because this fct is only exectued once
 	extractAddins "$addinsDir"
 
 	# create all the dir-tree to output folder
-	[ -v globoutput ] && { for i do [ -d "$i" ] && ([ "${globoutput#$(realpath "$i")}" = "$globoutput" ] || error "The --glob-output folder can't be inside an input folder."; cd -- "$i"; find -type d -exec mkdir -p "$globoutput/$(basename "$(realpath "$i")")/{}" \;); done;}
+	[ -v globoutput ] && { for i do [ -d "$i" ] && ([ "${globoutput#$(realpath "$i")}" = "$globoutput" ] || error "The --glob-output folder can't be inside an input folder."; cd -- "$i"; find . -type d -exec mkdir -p "$globoutput/$(basename "$(realpath "$i")")/{}" \;); done;}
 	# get absolute path, find all files (print size, filepath, input folderpath), sort (biggest size first), compress in parallel
 	{
 		# TODO parallel --memsuspend
-		realpath -z -- "$@" | xargs -0i find '{}' -type f ${globfilemask+-name "$globfilemask"} -printf '%s\0%P\0%H\0' | { [ -v globnosort ] && cat || sortFilesBySize;} | parallel -j${globjobs-100%} -0L3 --lb --bar compressFile {2} {3} {1} 1
+		realpath -z -- "$@" | xargs -0I{} find {} -type f ${globfilemask+-name "$globfilemask"} -printf '%s\0%P\0%H\0' | { [ -v globnosort ] && cat || sortFilesBySize;} | parallel -j${globjobs-100%} -0L3 --lb --bar compressFile {2} {3} {1} 1
 		# Thanks for the people helping me finding a way to sort by filesize (sorting by group of 3 elements): https://stackoverflow.com/a/76028193/13227011
 		# TODO don't compressFile duplicates (explicitly twice same input or implicitely - with the file and the parent folder)
 		# TODO test with filenames having $@-*
 
 		((s=SECONDS, h=s/3600, m=s/60-h*60, s%=60))
 		set -- $(<"$globstatsfile")
-		printf "\rCongrats! Processed %d files in %s and saved %sB (%.3f%%)!\n\a" $3 $(((h)) && printf ${h}h; ((m)) && printf ${m}m)${s}s $(numfmt --to=iec-i --format="%.2f" $1) $((1000000*$1/($2?$2:1)))e-4
+		printf "\rCongrats! Processed %d files in %s and saved %sB (%.3f%%)!\n\a" $3 $( ((h)) && printf ${h}h; ((m)) && printf ${m}m)${s}s $(numfmt --to=iec-i --format="%.2f" $1) $((1000000*$1/($2?$2:1)))e-4
 		rm -r "$globstatsfile" "$addinsDir" "$TMPDIR"
 	} &  # all the code is done in background so it won't be killed by Ctrl+C
 	while ! wait; do :; done  # each Ctrl+C will kill `wait` (1st hit: no new job, 2nd: kill parallel)
@@ -241,7 +251,7 @@ threadlimit() {
 					| awk '{print $2-$1, NR-1}' | sort -n | tail -$1 | cut -d' ' -f2 | paste -sd,) $$ >/dev/null
 }
 
-# input should be `find -printf '%s\0%P\0%H\0'`, output will be '%P\0%H\0%s\0' and elements sorted with largest %s first
+# input should be `find -printf '%s\0%P\0%H\0'`, output will be sorted with largest %s first
 sortFilesBySize() {
 	perl -0ne 'push @rec, $_; if ($#rec == 2) { push @items, join("", @rec); @rec = (); } END { print(join("", sort { $b <=> $a } @items)) }'
 }
@@ -365,8 +375,7 @@ compressFile() {	# warning: $1 can be empty
 			#  TODO for android APK: "aur/apk-resigner 1-2 (+8 0.00)		A bash script utility that resigns the Android Package (APK) files (Android applications) with different certificates."
 			# search "apk" or "android" with yay, because many utils exist to edit apk
 			# tested softwares: minizip-ng, 7z, kzip, leanify, ect
-			
-			# TODOOOOOOO input archived files do not keep their orig date
+
 			7z l -slt "$tmp" | grep '^Method = ' | grep -qve Store -e Deflate && p=  # at least one Method is not Store nor Deflate
 			v=$(mktemp -d)
 			7z x "$tmp" -o"$v" >/dev/null
@@ -504,8 +513,8 @@ compressFile() {	# warning: $1 can be empty
 			then # ect -1 ${globstrip+-strip} "$tmp"  # TODO (cannot strip using ECT since it drops all other frames - only 1st one is kept)
 				apngopt -z2 -i99${pnginsane+999} "$in" "$tmp" >/dev/null  # TODO to do better, we could split frames, use ECT --reuse, them remux
 			else mv "$tmp" "$tmp.png"
-				ect -9${pnginsane+9999} --mt-deflate -quiet ${globstrip+-strip} "$tmp.png"  # ect needs correct extension
-				# TODO tests, because -90059 is faster than -9999
+				ect -${pnginsane+8019}9 --mt-deflate -quiet ${globstrip+-strip} "$tmp.png"  # ect needs correct extension
+				# If the value is above 10000, the blocksplitting-compression cycle is repeated # / 10000 times. If # % 10000 is above 9, level 9 is used and the number of iterations of deflate compression per block is set to # % 10000. If # % 10000 is 9 or below, this number specifies the level.
 				mv "$tmp.png" "$tmp"
 			fi;;
 		image/webp)  # only tested cwebp; cwebp -z9 is NOT always the smallest one! Therefore just bruteforce -z (which is an alias for -m and -q options)
@@ -534,6 +543,8 @@ compressTmpFolder() {
 	[ -v globnoextract ] || find "$1" -type f -printf '%s\0%P\0%H\0' | sortFilesBySize | parallel -0L3 --lb compressFile {2} {3}
 }
 
+info() { printf "\033[1;36mI: %s\033[0m\n" "$1";}
+
 warning() { printf "\033[1;33mW: %s\033[0m\n" "$1" >&2;}
 
 error() { printf "\033[1;31mE: %s\033[0m\n" "$1" >&2; exit ${2:-1};}
@@ -546,7 +557,8 @@ ctrlCHandler() {
 		ctrlc=
 		{	kill -HUP $(pstree -ap $$ | grep parallel | grep -oP '^.*?\K[0-9]+') 2>/dev/null  # do NOT start any new job in any `parallel` (even grandchild processes)
 			sleep .1  # so the following msg will be shown *after* parallel's output about no new job
-			printf "\r%${COLUMNS}s\r\033[1;36mHit Ctrl+C again to stop all jobs.\033[0m\n" ''  # erase progress bar from parallel, then print msg
+			printf "\r%${COLUMNS}s\r" ''  # erase progress bar from parallel
+			info 'Finishing running jobs, hit Ctrl+C again to stop them.'
 		} &  # run in background so if we hit **again** Ctrl+C super fast (< .1 sec), ctrlCHandler won't be killed
 	fi
 }
