better info/warning/err

diff --git a/rhefo b/rhefo
--- a/rhefo
+++ b/rhefo
@@ -54,7 +54,7 @@ set -m  # All processes run in a separate process group (needed for Ctrl+C "tric
 version=0.0.1
 
 command_not_found_handle() {
-	warning "$1"$': command not found.\nInstall the needed package, this script will resume automatically.'
+	warning "$1: command not found." 'Install the needed package and this script will resume automatically.'
 	until command -v "$1" >/dev/null
 	do sleep 3;
 	done
@@ -168,7 +168,7 @@ find -name "*.flac" -type f -print0 | xargs -0 rhefo -o /outdir' |\
 
 # Will parse arguments, and then start the whole optimization process (if no errors in the arguments)
 parseArgs() {  # not using `local` vars because this fct is only exectued once
-	[ $(printf '\1' | od -dAn) = 1 ] || error 'This script was not tested on BIG ENDIAN devices. I mainly use `printf %x` with\nnumbers of up to 4 bytes.\nPLEASE, open an issue and if you have time HELP ME supporting this architecture\nby simply testing! This would really help a lot, since I only have little-endian\ndevices. Seriously, please.\n'
+	[ $(printf '\1' | od -dAn) = 1 ] || error 'This script was not tested on BIG ENDIAN devices. I mainly use `printf %x` with' 'numbers of up to 4 bytes.' 'PLEASE, open an issue and if you have time HELP ME supporting this architecture' 'by simply testing! This would really help a lot, since I only have little-endian' 'devices. Seriously, please.'
 	getopt -T && { error 'Your `getopt` is not compatible with this script. Open an issue.' 4;}
 	args=$(getopt -o hx:9j:klm:ESo:p:st:y -l help,extract-addins:,glob-insane,glob-jobs:,glob-keeptime,glob-lossy,glob-filemask:,glob-noextract,glob-nosort,glob-output:,glob-prefix:,glob-strip,glob-threads:,glob-tmp:,glob-update,flac-insane,flac-lossy,flac-subset,gzip-insane,gzip-lossy,mp3-lossy,png-insane,zip-insane -n rhefo -s bash -- "$@")
 	(($?)) && error 'Could not parse args. See the help message `rhefo -h`.'
@@ -229,7 +229,7 @@ parseArgs() {  # not using `local` vars because this fct is only exectued once
 
 		((s=SECONDS, h=s/3600, m=s/60-h*60, s%=60))
 		set -- $(<"$globstatsfile")
-		printf "\rCongrats! Processed %d files in %s and saved %sB (%.3f%%)!\n\a" $3 $( ((h)) && printf ${h}h; ((m)) && printf ${m}m)${s}s $(numfmt --to=iec-i --format="%.2f" $1) $((1000000*$1/($2?$2:1)))e-4
+		info "$(printf "Congrats! Processed %d files in %s and saved %sB (%.3f%%)!\a" $3 $( ((h)) && printf ${h}h; ((m)) && printf ${m}m)${s}s $(numfmt --to=iec-i --format="%.2f" $1) $((1000000*$1/($2?$2:1)))e-4)"
 		rm -r "$globstatsfile" "$addinsDir" "$TMPDIR"
 	} &  # all the code is done in background so it won't be killed by Ctrl+C
 	while ! wait; do :; done  # each Ctrl+C will kill `wait` (1st hit: no new job, 2nd: kill parallel)
@@ -276,37 +276,6 @@ catchSmallestFile() {
 	a=${a#* }
 	mv "$a" "${a%.*}"
 	rm -f "$@"  # -f to not print err msg, since there's a missing file ("$a") 
-}
-
-# Using ffmpeg, extract each stream to a separate file, compress the streams, and finally remux all of them with the correct metadata. $1 is the fullpath; $2 is blacklist of streams to not optimize (mp3, mjpeg, ...)
-# TODO $2
-ffCompressStreams() {
-	local i=0 c f name=${1##*/} IFS=/ tmp=${1%/*}/a${1##*/}
-	c=$(AV_LOG_FORCE_COLOR=1 ffmpeg -v warning -i "$1" -map 0 -f null - 2>&1 >/dev/null)  # check for malformed streams/file
-	if (($?)) || [ "$c" ]
-	then echo -e "\r\e[1;41m$1: got warning or error while parsing. Could not extract streams.\e[0m\n$c"
-		return 1
-	fi
-	cd "${1%/*}"  # trick in order to use IFS=/ as a separator since that char is not allowed in filenames
-	while read -r c
-	do f+="-map/0:$i/-c/copy/$name.$((i++)).$c/"  # TODO see if we can inline that with the ffmpeg command; at least I'm sure with can inline with ffprobe
-	done < <(ffprobe -v warning -show_entries stream=codec_name -of default=nk=1:nw=1 "$1")  # `-of csv=p=0` doesn't work if stream has SIDE_DATA (it would have a trailing ',')
-	ffmpeg -v warning -i "$1" $f
-	f=
-	while ((i--))
-	do	compressFile "$name.$i".*  # will expand automatically to the correct file ext
-		c+="-i/"
-		c+="$name.$i".*  # TODO see if inline is possible, and check if works when mixing (c[0] then f[0] then c[1] ...)
-		c+=/
-		f+="-map_metadata:s:$i/0:s:$i/-map/$((i+1))/"
-	done
-	mv "$1" "$tmp"
-	# TODO ffmpeg will override `encoder` metadata (global metadata)
-	ffmpeg -v warning -i "$tmp" $c $f -c copy -fflags +bitexact "$1"
-	rm "$tmp" "$1".*
-	# ffmpeg -i fuckedup.mp3 -i p.mp3 -i second.jpg -i first.jpg -map_metadata:s:0 0:s:0 -map 1 -map_metadata:s:1 0:s:1 -map 2 -map_metadata:s:2 0:s:2 -map 3 -fflags +bitexact -codec copy fffout.mp3
-	cd - >/dev/null
-	# [ ${globnotest-x} ] && [ "$()" != "$()" ] && { echo "$tmp: recompression was NOT lossless. You should open an issue. Input file was kept.">&2; mv "9$tmp" "$tmp";}  #TODO
 }
 
 # $1=filepath	$2=prefixpath	$3=filesize		("$2/$1" = full absolute input path)	(do NOT set $3 when this is a subcall from another compressFile - e.g. when compressFile a file from an extracted ZIP file); none can have spaces
@@ -531,7 +500,7 @@ compressFile() {	# warning: $1 can be empty
 	[ -v globkeeptime ] && touch -md"$mtime" "$tmp" && touch -ad"$atime" "$tmp"
 	if [ $3 ]
 	then sem --fg --id "$globstatsfile" 'set -- $(<"$globstatsfile"); printf "$(('$size'+$1))\n$(('$3'+$2))\n$((1+$3))\n" >"$globstatsfile"'  # use a semaphore to allow only one thread to write stats at a time
-		[[ -v globoutput && ! -v globupdate && -e "$out" ]] && { warning "'$out' already exists, not updated. Compressed version here: '$tmp'.\nRerun with -y to overwrite files in output directory, or with -p to add a prefix.";} || { mv "$tmp" "$out"; chown -f --reference="$in" "$out"; chmod -f --reference="$in" "$out";}
+		[[ -v globoutput && ! -v globupdate && -e "$out" ]] && { warning "'$out' already exists, not updated. Compressed version here: '$tmp'." 'Rerun with -y to overwrite files in output directory, or with -p to add a prefix.';} || { mv "$tmp" "$out"; chown -f --reference="$in" "$out"; chmod -f --reference="$in" "$out";}
 	else mv "$tmp" "$out"
 	fi
 	cd /
@@ -543,11 +512,16 @@ compressTmpFolder() {
 	[ -v globnoextract ] || find "$1" -type f -printf '%s\0%P\0%H\0' | sortFilesBySize | parallel -0L3 --lb compressFile {2} {3}
 }
 
-info() { printf "\033[1;36mI: %s\033[0m\n" "$1";}
+info() { printf "\r\033[1;36mI: %s\033[0m\n" "$@";}
 
-warning() { printf "\033[1;33mW: %s\033[0m\n" "$1" >&2;}
+warning() { printf "\r\033[1;33mW: %s\033[0m\n" "$@" >&2;}
 
-error() { printf "\033[1;31mE: %s\033[0m\n" "$1" >&2; exit ${2:-1};}
+error() {
+	if [[ ${@: -1} = +([0-9]) ]]  # check if last arg is a number (== exit code)
+	then printf "\r\033[1;31mE: %s\033[0m\n" "${@:1:$#-1}" >&2; exit ${@: -1}
+	else printf "\r\033[1;31mE: %s\033[0m\n" "$@" >&2; exit 1
+	fi
+}
 
 ctrlCHandler() {
 	if [ -v ctrlc ]
